FROM drachtio/drachtio-freeswitch-mrf:latest AS freeswitch-base

FROM debian:bookworm-slim AS builder

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    pkg-config \
    libssl-dev \
    zlib1g-dev \
    libcurl4-openssl-dev \
    libcjson-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN git clone https://github.com/nats-io/nats.c && \
    cd nats.c && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd /tmp && rm -rf nats.c

COPY --from=freeswitch-base /usr/local/freeswitch/include/freeswitch/ /tmp/freeswitch_headers/

WORKDIR /workspace
COPY Makefile .
COPY src/ src/
COPY include/ include/
COPY lib/ lib/

RUN make DRIVER=nats clean all

FROM drachtio/drachtio-freeswitch-mrf:latest

RUN apt-get update && apt-get install -y \
    libcjson1 \
    libssl3 \
    libcurl4 \
    zlib1g \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/libnats.so* /usr/local/lib/
COPY --from=builder /workspace/mod_event_agent.so /usr/local/freeswitch/mod/

RUN ldconfig

COPY autoload_configs/mod_event_agent.conf.xml /usr/local/freeswitch/conf/autoload_configs/

RUN sed -i '/<\/modules>/i \    <load module="mod_event_agent"\/>/' /usr/local/freeswitch/conf/autoload_configs/modules.conf.xml

# Insert NATS environment variables into vars.xml (before closing </include>)
RUN sed -i 's|</include>|  <!-- mod_event_agent NATS configuration -->\n  <X-PRE-PROCESS cmd="env-set" data="agent_node_id=\$AGENT_NODE_ID"/>\n<X-PRE-PROCESS cmd="env-set" data="nats_host=\$NATS_HOST"/>\n  <X-PRE-PROCESS cmd="env-set" data="nats_port=\$NATS_PORT"/>\n</include>|' /usr/local/freeswitch/conf/vars.xml

# Set default environment variables
ENV NATS_HOST=localhost
ENV NATS_PORT=4222
ENV AGENT_NODE_ID=agent-node-1


# Puertos de red
EXPOSE 5060/udp 5060/tcp 5080/tcp 8021/tcp 16384-32768/udp
EXPOSE 5066/tcp 7443/tcp 8081/tcp 8082/tcp

CMD ["freeswitch", "-nonat", "-c"]
